Outletshop/Outletshop/Models/Database/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Outletshop.Models.Database
{
    public partial class Order
    {
        [Key, ForeignKey("orderItems")]
        public int orderId { get; set; }
        public DateTime? orderDate { get; set; }
   
        [DisplayName("Fornavn")]
        public string firstName { get; set; }
        [DisplayName("Efternavn")]
        public string lastName { get; set; }
        [DisplayName("E-mail adresse")]
        public string Email { get; set; }
        [DisplayName("Telefon nr")]
        public string phone { get; set; }
        [DisplayName("Postnr")]
        public string postalCode { get; set; }
        [DisplayName("By")]
        public string city { get; set; }


        public virtual ICollection<OrderItem> orderItems { get; set; }

        public virtual OrderItem orderItem { get; set; }

        public Order()
        {
            orderItems = new List<OrderItem>();

        }
        

    }
}

Outletshop/Outletshop/Controllers/CartController.cs
using Outletshop.Models.Database;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Outletshop.Controllers
{
    public class CartController : Controller
    {





        public Connection db = new Connection();


        // GET: Cart
        public ActionResult Order()
        {
            List<Item> cart = (List<Item>)Session["cart"];
            Session["cart"] = cart;

            return View();
        }
        public ActionResult Checkout(Order order)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            Session["cart"] = cart;

            return View();
        }

        public ActionResult Accept(Order order)
        {

            order.orderItems = new List<OrderItem>();
            var cart = (List<Item>)Session["cart"];


            foreach (var item in cart)
            {
                var ord = new Order()
                {

                    firstName = order.firstName,
                    lastName = order.lastName,
                    Email = order.Email,
                    phone = order.phone,
                    postalCode = order.postalCode,
                    city = order.city
                };


                var itemOrder = new OrderItem
                {

                    orderName = item.Product.productName,
                    salePrice = item.Product.consignment.salePrice,
                    quantity = item.Quantity,

                };


                ((List<OrderItem>)order.orderItems).Add(itemOrder);


            }

            db.Orders.Add(order);

            db.SaveChanges();

            return View();
        }



        private int isExisting(int? id)
        {
            List<Item> cart = (List<Item>)Session["cart"];

            if (cart.Count > 0)
            {
                for (int i = 0; i < cart.Count; i++)
                    if (cart[i].Product.productId == id)
                        return i;
            }

            if (cart.Count < 0)
            {
                for (int i = 0; i < cart.Count; i--)
                    if (cart[i].Product.productId == id)
                        return i;
            }


            return -1;
        }

        public ActionResult Delete(int? id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            Item item = cart.FirstOrDefault(l => l.Product.productId == id);


            if (item != null)
            {
                if (item.Quantity > 0)
                {
                    item.Quantity--;
                }

                if (item.Quantity == 0)
                {
                    cart.RemoveAt(index);
                }
            }

            Session["cart"] = cart;




            return RedirectToAction("Order");

        }





        public ActionResult OrderNow(int? id, string quantity)
        {

            if (id == null)
            {

                ViewBag.Message = "Kurvenen er tom!";

            }

            if (string.IsNullOrEmpty(Session["cart"] as string))
            {
                ViewBag.Message = "Kurvenen er tom!";
            }

            if (Session["cart"] == null)
            {

                List<Item> cart = new List<Item>();
                cart.Add(new Item(db.Products.Find(id), 1));

                Session["cart"] = cart;
            }

            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);

                if (index == -1)
                {
                    cart.Add(new Item(db.Products.Find(id), 1));

                }

                else
                {
                    cart[index].Quantity++;


                    Session["cart"] = cart;

                }




            }

            return RedirectToAction("Order");
        }





    }


}

Outletshop/Outletshop/Controllers/OrderController.cs
using Outletshop.Models.Database;
using Outletshop.Models.Interface;
using Outletshop.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Outletshop.Controllers
{
    public class OrderController : Controller
    {
        private Connection db = new Connection();

        IOrderRepository _repository;

        public OrderController() : this(new OrderRepossitory())
        {

        }

        public OrderController(IOrderRepository repository)
        {
            _repository = repository;
        }

        public ActionResult Index()
        {
            ViewData["ControllerName"] = this.ToString();
            return View("Index", _repository.GetAllOrders());
        }


    }
}

Outletshop/Outletshop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Outletshop.Models.Interface;
using Outletshop.Models.Repository;
using Outletshop.Models.Database;
using System.Threading.Tasks;
using System.Net;
using System.Data.Entity.Infrastructure;
using System.Data.Entity;
using System.Threading;

namespace Outletshop.Controllers
{
    public class ProductsController : Controller
    {
        private Connection db = new Connection();

        IProductsRepository _repository;

        public ProductsController() : this(new ProductsRepository())
        {

        }

        public ProductsController(IProductsRepository repository)
        {
            _repository = repository;
        }

        // GET: Products
        public ActionResult Index()
        {
            ViewData["ControllerName"] = this.ToString();
            return View("Index", _repository.GetAllProducts());
        }

       



        public ActionResult View(int? id)
        {
           

            var query =  (from b in db.Products where b.productId == id select b).ToList();

            foreach (var item in query)
            {
                ViewBag.getStock = Convert.ToInt32(item.consignment.stock);

                // int getStock = Convert.ToInt32(item.consignment.stock);

                //ViewBag.getStock = getStock;

                if (ViewBag.getStock > 1)
                {
                    // ViewBag.Message = "På lager ";

                    var list = new List<int>();
                    for (int i = 1; i <= ViewBag.InStock; i++)
                    {

                        list.Add(i);

                    }

                    SelectList selectedList = new SelectList(list);
                    ViewBag.DdList = selectedList.ToString();



                }

                else if (ViewBag.getStock <= 0)
                {
                    ViewBag.Message = "Ikke på lager";
                }

                // foreach ends
            }


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }



            Product pro =  _repository.GetProductById(id);



            if (pro == null)
            {
                return HttpNotFound();
            }

            return View("View", pro);
            
        }

        [HttpPost, ActionName("View")]
        public ActionResult View(int? id, string quantity)
        {
            quantity = Request.Form["quantity"];
            Session["Qty"] = quantity;

            ViewBag.Session = Session["Qty"];


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var StockToUpdate =  _repository.GetProductById(id);

            try
            {
                if (string.IsNullOrEmpty(Session["quantity"] as string))
                {
                    ViewBag.Message = "Kurvenen er tom!";
                }

                else
                {
                   

                    List<Item> Quantity = (List<Item>)Session["Qty"];

            


                }

   

            }
            catch (Exception)
            {


                throw;
            }

            return View(StockToUpdate);
        }
    }

 


    //    public ActionResult Create()
    //    {
    //        return View("Create");
    //    }

    //    [HttpPost]
    //    public ActionResult Create(ConsignmentProduct viewModel, string filename)
    //    {


    //        try
    //        {
    //            if (ModelState.IsValid)
    //            {
    //                _repository.CreateConsignment(viewModel, filename);
    //                return RedirectToAction("ProductList");
    //            }

    //        }
    //        catch (Exception ex)
    //        {

    //            ModelState.AddModelError("", ex);
    //            ViewData["CreateError"] = "Unable to create; view innerexception";
    //        }

    //        return View("Create");
    //    }
}

Outletshop/Outletshop/Views/Cart/Accept.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Accept</title>
</head>
<body>
    <div> 

        Tak for din ordre, vi har sendt dig en bekræftelsesmail. 
    </div>
</body>
</html>

Outletshop/Outletshop/Views/Cart/Cart.cshtml
@{
    Layout = null;
}

@using Outletshop.Controllers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
<body>
    <div>
        <table cellpadding="2" , cellspacing="2" border="1">

            <tr>
                <th>
                    delete
                </th>
                <th>
                    Id
                </th>
                <th>
                    ProductName
                </th>
                <th>
                    Product Price
                </th>
                <th>
                    Quanty
                </th>
                <th>
                    Total
                </th>

            </tr>

            @foreach (Item item in (List<Item>)Session["cart"])
            {
                <tr>
                    <td>@Html.ActionLink("Delete", "Delete", "Cart", new { id = item.Product.productId }, null)</td>
                    <td>@item.Product.productId</td>
                    <td>@item.Product.productName</td>
                    <td>@item.Product.consignment.salePrice</td>
                    <td>@item.Quantity</td>
                    <td>@(item.Product.consignment.salePrice * item.Quantity)</td>





                </tr>

            }
            @Html.ActionLink("Fortsæt", "Index", "Products");

        </table>
    </div>
</body>
</html>

Outletshop/Outletshop/Views/Cart/Checkout.cshtml
@model Outletshop.Models.Database.ItemOrder
@using Outletshop.Controllers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CheckOut</title>
</head>
<body>
  
@using (Html.BeginForm("Accept", "Cart"))
{
    <div class="col-md-6">
        <h1>
            Kunde informationer
        </h1>
        <br />

        <div class="form-group">

            @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Fornavn" } })

        </div>

        <div class="form-group">

            @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Efternavn" } })

        </div>

        <div class="form-group">

            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "E-mail adresse" } })

        </div>

        <div class="form-group">

            @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Telefonnummer" } })

        </div>

        <div class="form-group">

            @Html.EditorFor(model => model.postalCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Postnr" } })

        </div>

        <div class="form-group">

            @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control", @placeholder = "By" } })

        </div>












    </div>
        <div class="col-md-6">

            <h1>
                Order bestilling
            </h1>
            <br />



            @foreach (Item item in (List<Item>)Session["cart"])
            {

               <text>Produktnavn -</text> @item.Product.productName <br />
            <text>Produktpris -</text>  @item.Product.consignment.salePrice<br />
            <text>Produkt antal -</text>  @item.Quantity<br /><hr />

            }


        </div>
        <div class="col-md-12">

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>

}















</body>
</html>

Outletshop/Outletshop/Views/Cart/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Outletshop/Outletshop/Views/Cart/Order.cshtml
@using Outletshop.Controllers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
<body>

        
            <div>
                <div class="col-md-10">
       
                    @Html.ActionLink("Fortsæt med at shoppe", "Index","Products")
                </div>
                <div class="col-md-2 pull-right">
                    @Html.ActionLink("Til kassen", "Checkout", "Cart")
                </div>

    
                <br>
                <br>
                <br>

                <table class="table">

                    <tr>
                        <th>
                            Slet
                        </th>
                        @*<th>
                            Id
                        </th>*@
                        <th>
                            Produktnavn
                        </th>
                        <th>
                            Produktpris
                        </th>
                        <th>
                            Antal
                        </th>
                        <th>
                            Total
                        </th>

                    </tr>



                    @foreach (Item item in (List<Item>)Session["cart"])
                        {

                            <tr>
                                <td>@Html.ActionLink(" ", "Delete", "Cart", new { id = item.Product.productId,  }, new { @class = "glyphicon glyphicon-trash" })</td>
                                @*<td>@item.Product.productId</td>*@
                                <td>@item.Product.productName</td>
                                <td>@item.Product.consignment.salePrice</td>
                                <td>@item.Quantity</td>
                                <td>@(item.Product.consignment.salePrice * item.Quantity)</td>


                            </tr>


                            }


                </table>




            </div>



    @ViewBag.Session

</body>
</html>